# Generated by Django 3.2.14 on 2023-05-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0002_auto_20230527_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('Web Developer', 'Web Developer'), ('Android Developer', 'Android Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapiapp.company')),
            ],
        ),
    ]
